# Generated by Django 2.2.9 on 2022-12-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220609_1313'),
        ('posts', '0002_auto_20221127_2100'),
    ]

    operations = [
    ]
